#!/bin/bash
# Apply Caddy config: regenerate etc/Caddyfile.imports, validate, reload.
#
# Uses the mounted etc/apply_from_mac.sh when /Volumes/Container is available;
# otherwise does the same work over SSH — no SMB mount or credential needed.
# Validation runs before the reload either way, so a bad .caddy leaves the
# live config untouched.

set -euo pipefail

ETC_MAC="/Volumes/Container/caddy/etc"
ETC_NAS="/share/CACHEDEV1_DATA/Container/caddy/etc"
DOCKER="/share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker"

if [ -d "$ETC_MAC" ]; then
    cd "$ETC_MAC" && exec ./apply_from_mac.sh
fi

echo "SMB mount absent — applying over SSH..."
ssh nas bash -s <<EOF
set -euo pipefail
cd '$ETC_NAS'
{
    printf '# Auto-generated imports - DO NOT EDIT MANUALLY\n# Regenerated by apply-caddy.sh (SSH)\n\n'
    find ../www -maxdepth 2 -name '*.caddy' -type f | while read -r f; do
        printf 'import /var/www/%s/*.caddy\n' "\$(basename "\$(dirname "\$f")")"
    done | sort -u
} > Caddyfile.imports.tmp
mv Caddyfile.imports.tmp Caddyfile.imports
$DOCKER exec caddy-porkbun caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
$DOCKER exec caddy-porkbun caddy reload --config /etc/caddy/Caddyfile --address localhost:2019
EOF
