from datetime import datetime
from collections import defaultdict


def group_by_type(findings):
    grouped = defaultdict(list)
    for detector_name, detector_findings in findings.items():
        for finding in detector_findings:
            grouped[finding['type']].append(finding)
    return grouped


def format_finding(finding):
    file_ref = f"`{finding['file']}:{finding['line']}`" if finding['line'] > 0 else f"`{finding['file']}`"
    return f"- {file_ref} - {finding['message']}"


def generate_summary(grouped_findings):
    total = sum(len(findings) for findings in grouped_findings.values())

    type_names = {
        'deprecated_pattern': 'Deprecated Patterns',
        'mixed_conventions': 'Mixed Conventions',
        'dead_code': 'Dead Code Paths',
        'duplicate_code': 'Duplicate Methods'
    }

    lines = [
        "## Summary\n",
        f"- **Total Issues**: {total}"
    ]

    for type_key, type_name in type_names.items():
        count = len(grouped_findings.get(type_key, []))
        lines.append(f"- **{type_name}**: {count}")

    return '\n'.join(lines)


def generate_section(type_key, findings):
    if not findings:
        return ""

    type_names = {
        'deprecated_pattern': 'Deprecated Patterns',
        'mixed_conventions': 'Mixed Conventions',
        'dead_code': 'Dead Code Paths',
        'duplicate_code': 'Duplicate Methods'
    }

    lines = [
        f"\n## {type_names.get(type_key, type_key)} ({len(findings)} issues)\n"
    ]

    severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3}
    sorted_findings = sorted(findings, key=lambda f: (severity_order.get(f['severity'], 4), f['file'], f['line']))

    lines.extend(format_finding(f) for f in sorted_findings)

    return '\n'.join(lines)


def generate_report(findings, output_path, repo_path):
    grouped = group_by_type(findings)

    report_lines = [
        "# Repository Analysis Report\n",
        f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        f"**Repository**: `{repo_path}`\n",
        generate_summary(grouped)
    ]

    type_order = ['deprecated_pattern', 'mixed_conventions', 'dead_code', 'duplicate_code']
    for type_key in type_order:
        if type_key in grouped:
            report_lines.append(generate_section(type_key, grouped[type_key]))

    report_lines.append("\n---\n")
    report_lines.append("*Generated by repomap-analyzer skill*")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(report_lines))
